
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 08 18:32:35 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 34;
  public static final int CONST = 42;
  public static final int CHAR = 37;
  public static final int MUL_EQUAL = 28;
  public static final int LOWER = 22;
  public static final int CONTINUE = 47;
  public static final int LPAREN = 6;
  public static final int GREATER = 18;
  public static final int SEMI = 5;
  public static final int FOR = 45;
  public static final int MINUS = 13;
  public static final int STATIC = 48;
  public static final int RPAREN = 7;
  public static final int AND = 24;
  public static final int OR = 25;
  public static final int BOOL = 38;
  public static final int COMMA = 8;
  public static final int CLASS = 41;
  public static final int INC = 31;
  public static final int DIV = 15;
  public static final int PLUS_EQUAL = 26;
  public static final int MINUS_EQUAL = 27;
  public static final int DIV_EQUAL = 29;
  public static final int PLUS = 12;
  public static final int IF = 49;
  public static final int IS_EQUAL = 19;
  public static final int DOT = 33;
  public static final int IS_NOT_EQUAL = 21;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 35;
  public static final int EQUAL = 11;
  public static final int GREATER_EQUAL = 20;
  public static final int NEW = 43;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int NUMBER = 36;
  public static final int MOD = 17;
  public static final int BREAK = 40;
  public static final int IDENT = 39;
  public static final int VOID = 16;
  public static final int MOD_EQUAL = 30;
  public static final int ELSE = 50;
  public static final int LBRACE = 3;
  public static final int READ = 44;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 46;
  public static final int LOWER_EQUAL = 23;
  public static final int PROG = 2;
  public static final int DEC = 32;
  public static final int PRINT = 9;
}

